---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

In STAT 331, I have learned to utilize the tools used to process data using R. I think that learning how to use R to do the things in this class has helped my skills as a data scientist develop, especially in communicating the results. I think the main thing that I took away from this class other than the skills that were part of the course, was the importance of making accessible visualizations, like tables and graphs, to communicate the story or meaning to the reader. It helped me realize smaller things that I would have realized, such as not having the reader rotate their head, which helps make graphs more accessible. It helped me improve my skills in making a thing that works well, rather than a thing that just works. I think this can be shown in my earlier work, compared to some of my later work. Furthermore, previous to this class, I tended to focus on the end result more than the steps it took to get there. I have learned that in this course, having efficient, tidy, and reproducible code is part of the process and helps with communicating the results to others. Using code that is efficient and nice to read(PE-1, DVS-1-1&2) helps to communicate the message.
