---
title: "The Power of Efficiency"
format: html
editor: visual
---

As we’ve said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term “efficiency” means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Your essay should address the following questions:

-   What is the definition of “efficiency”?

-   What does efficiency look like in statistical computing / data science?

-   What does efficiency allow you to do?

-   Why is efficiency important?

-   Where did you encounter efficiency, and what were some [“a-ha” moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

Efficiency is using your resources in the best way to do a job. In a data science or statisical computing context, efficiency is writing code that works as quickly and with the least amount of resources as possible. We can achieve this by reducing redundancies and using functions that contact the processor fewer times, while still doing the same job This can be shown in using only one function call to do multiple things, such as filtering for multiple strings with one function call(PE -1), rather than with one for each string that needed to be filtered, as well as using functions when repeating the same code multiple times. This was an a-ha moment for me, as in my previous R experience, I did not know that you could just list the different filters, mutates, etc. The demonstration of efficiency in class, with the demonstration of the code communicating to the processors, and showing that the functions we learned in class were more efficient than using a bunch of loops, was also a big aha moment(PE-3 across()). Efficiency allows for larger and more complex data sets to be processed and communicated to an audience, in a timely manner and without eating all of your computer's resources. Code that is more efficient helps with managing time and resources.
